openapi: 3.1.0
info:
  title: "ihavefood"
  description: "Chiang Mai district only [Mueang,Hang Dong,San Sai,Mae Rim,Doi Saket]"
  version: 0.1.0
servers:
    - url: "http://localhost:180"
      description: "TODO TODO TODO TODO TODO"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    basicAuth:
      type: http
      scheme: basic
      
paths:

#---------------Auth Service--------------------
  /auth/register:
    $ref: 'authservice/register.yaml'
  /auth/login:
    $ref: 'authservice/login.yaml'
  /auth/users/roles:
    $ref: 'authservice/users.roles.yaml'



#---------------Profile Service-----------------
  /api/profiles/{username}:
    $ref: 'profileservice/users.username.yaml'
  /api/profiles:
    $ref: 'profileservice/users.yaml'




#---------------Order Service-----------------
  /api/orders/place-order:
    $ref: 'orderservice/orders.placeorder.yaml'
  /api/orders/{username}:
    $ref: 'orderservice/orders.username.yaml'




#---------------Delivery Service-----------------
  /api/deliveries/riders/accept:
    $ref: 'deliveryservice/deliveries.riders.accept.yaml'





#---------------Restaurant Service-----------------
  /api/restaurants/{restaurantId}:
    $ref: 'restaurantservice/restaurants.id.yaml'
  /api/restaurants:
    $ref: 'restaurantservice/restaurants.yaml'
  /api/restaurants/menus:
    $ref: 'restaurantservice/restaurants.menus.yaml'




#---------------Coupon Service-----------------
  /api/coupons:
    $ref: 'couponservice/coupons.yaml'
  /api/coupons/{code}:
    $ref: 'couponservice/coupons.code.yaml'






#---------------END-----------------

