openapi: 3.1.0
info:
  title: "ihavefood"
  description: "Chiang Mai district only [Mueang,Hang Dong,San Sai,Mae Rim,Doi Saket]"
  version: 0.1.0
servers:
    - url: "http://localhost:180"
      description: "TODO TODO TODO TODO TODO"
      
paths:

#---------------Auth Service--------------------
  /auth/register:
    $ref: 'authservice/register.yaml'

  /auth/login:
    $ref: 'authservice/login.yaml'

  /auth/users/roles:
    $ref: 'authservice/users.roles.yaml'



#---------------Profile Service-----------------
  /api/profiles/{username}:
    $ref: 'profileservice/profiles.username.yaml'
  /api/profiles:
    $ref: 'profileservice/profiles.yaml'



#---------------Order Service-----------------
  /api/orders/place-order:
    $ref: 'orderservice/placeorder.yaml'
  /api/orders/{username}:
    $ref: 'orderservice/orders.username.yaml'




#---------------Delivery Service-----------------
  /api/deliveries/riders/accept:
    $ref: 'deliveryservice/riders.accept.yaml'


#---------------Restaurant Service-----------------
  /api/restaurants/{restaurantId}:
    $ref: 'restaurantservice/restaurants.id.yaml'
  /api/restaurants:
    $ref: 'restaurantservice/restaurants.yaml'
  /api/restaurants/menus:
    $ref: 'restaurantservice/menus.yaml'


#---------------Coupon Service-----------------
  /api/coupons:
    $ref: 'couponservice/coupons.yaml'
  /api/coupons/{code}:
    $ref: 'couponservice/coupons.code.yaml'


components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
        #    BasicAuth:
        #      type: http
        #      scheme: basic

# Apply Bearer Authentication every apis(global)
security:
  - BearerAuth: []
#---------------END-----------------
